### ISSUE TITLE
No module named 'typing'

### ISSUE THREAD

**Issue by Sevift** [rytilahti/python-mirobo#24]
pi@raspberrypi:~ $ mirobo discover
Traceback (most recent call last):
  File "/usr/local/bin/mirobo", line 7, in <module>
    from mirobo.cli import cli
  File "/usr/local/lib/python3.4/dist-packages/mirobo/__init__.py", line 2, in <module>
    from mirobo.protocol import Message, Utils
  File "/usr/local/lib/python3.4/dist-packages/mirobo/protocol.py", line 6, in <module>
    from typing import Any, Dict, Tuple
ImportError: No module named 'typing'

pi@raspberrypi:~ $ python3 --version
Python 3.4.2

**Comment by Sevift** [comment]
You must have Python 3.5

**Comment by rytilahti** [comment]
You can also install 'typing' package, I suppose. I'll add the dependency and bump the version, please re-open if this doesn't help :)
