### ISSUE TITLE
CLI tool demands an IP address always

### ISSUE THREAD

**Issue by syssi** [rytilahti/python-mirobo#36]
It looks like I'm unable to work appropriate with the cli tool. ;-)

```
$ ./mirobo discover
Usage: mirobo [OPTIONS] COMMAND [ARGS]...

Error: Invalid value for "--ip": Invalid IP: None does not appear to be an IPv4 or IPv6 address

$ ./mirobo --ip 192.168.13.1 discover
Traceback (most recent call last):
  File "./mirobo", line 11, in <module>
    load_entry_point('python-mirobo==0.1.2', 'console_scripts', 'mirobo')()
  File "/home/sebastian/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sebastian/.local/lib/python3.5/site-packages/click/core.py", line 696, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/home/sebastian/.local/lib/python3.5/site-packages/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/home/sebastian/.local/lib/python3.5/site-packages/click/core.py", line 1018, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/home/sebastian/.local/lib/python3.5/site-packages/click/core.py", line 880, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/sebastian/.local/lib/python3.5/site-packages/click/core.py", line 1404, in handle_parse_result
    self.callback, ctx, self, value)
  File "/home/sebastian/.local/lib/python3.5/site-packages/click/core.py", line 78, in invoke_param_callback
    return callback(ctx, param, value)
  File "/home/sebastian/.local/lib/python3.5/site-packages/mirobo/vacuum_cli.py", line 32, in validate_token
    token_len = len(value)
TypeError: object of type 'NoneType' has no len()
```

Do I miss something? The behaviour is the same for version 0.1.2 and the current master. Thanks in advance!

**Comment by rytilahti** [comment]
Thanks, this was somehow overlooked.

**Comment by syssi** [comment]
Thanks! :+1:
