### ISSUE TITLE
Bug when having multiple network interfaces (discovery)

### ISSUE THREAD

**Issue by pixeye33** [rytilahti/python-mirobo#9]
i feel kinda dumb but i'm not succeding to make it work...

```
(homeassistant) homeassistant@hassbian:~/.homeassistant/config $ mirobo discover
INFO:mirobo.vacuum:Sending discovery to <broadcast> with timeout of 5s..
INFO:mirobo.vacuum:Discovery done
```

Maybe i found a bug ?
My raspberry is wired, and i connect to it via SSH via cable.
If i a laptop on the robot's wifi and start a "mirobo discover" from the raspberry, i see no broadcast UDP packet. With the same laptop connected on my wired network i see the broadcasts. (of course my robot doesnt see the requests and doesnt give out the token)

My guess is that the discovery packet isnt using my wlan0 connection. maybe adding a interface parameter would be good ?

I think i've finally got the token (via : https://github.com/rytilahti/python-mirobo/issues/5#issuecomment-298165119) but when i try to use it i get :
```
mirobo --ip 10.11.0.78 --token 4D61447643524D63
ERROR:mirobo.vacuum:got error when receiving: timed out
Traceback (most recent call last):
  File "/srv/homeassistant/bin/mirobo", line 11, in <module>
    sys.exit(cli())
  File "/srv/homeassistant/lib/python3.4/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/srv/homeassistant/lib/python3.4/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/srv/homeassistant/lib/python3.4/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/homeassistant/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/mirobo/cli.py", line 46, in cli
    ctx.invoke(status)
  File "/srv/homeassistant/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/mirobo/cli.py", line 59, in status
    res = vac.status()
  File "/srv/homeassistant/lib/python3.4/site-packages/mirobo/vacuum.py", line 150, in status
    return VacuumStatus(self.send("get_status")[0])
  File "/srv/homeassistant/lib/python3.4/site-packages/mirobo/vacuum.py", line 121, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out
```

But if i use the ip of my laptop (on my home wifi, same as the one now used by the robot), i can see the packets sent by mirobot command line...

here is how i got the token :
![rg_mfdo1xe_h9k5uibqenwsfjwcx44sgimqp4ieo2zpt_klo4qg7atj7bcc1neziilpq8wrkdu8vzbwcjjjypj3ye3_xqpt50sxz3g3_h3pxem5_flizzqtgterzkv1bbtgr9rbsn4r0xd6jtzsrxa69r-uru3pnnnoozzk6qztzys2i0c2srybvytxllpcyw_7dscwmyuvtfiznuq2r](https://cloud.githubusercontent.com/assets/1382471/26220874/ba69f44e-3c14-11e7-96e5-5e2bb4b35052.png)

or do i miss something ?

**Comment by rytilahti** [comment]
The token should be 32 characters wide, so the one you are using is too small. Anyway, it's on my todo to add a possibility to use the robot IP directly instead of broadcast, as that doesn't seem to work unproblematic on all systems.

How did you connect your wired raspberry to the wifi? If you didn't it's not a surprise it doesn't receive those packets :)

**Comment by pixeye33** [comment]
Well https://github.com/rytilahti/python-mirobo/issues/5#issuecomment-298165119 sait last 16 characters... with 32 it works now !
Thanks for that :)

for the wifi, i did with wpa_cli, iwconfig says i'm connected, ifconfig says that wlan0 got an IP, and, i can ping the robot. 
But maybe i have to do something on top of that ?

**Comment by rytilahti** [comment]
Glad to hear it, I created an issue to add an error message when the token seems invalid.
